name: Build and Deploy Spring Boot App

on:
  push:
    branches: [ "main" ]  # Change to your branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: |
          echo "Current directory:"
          pwd
          echo "Files here:"
          ls -la
          cd spring_github_copilot
          echo "Inside spring_github_copilot:"
          pwd
          ls -la
          ./mvn clean package -DskipTests

      - name: Upload JAR to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: springboot-ec2-terraform/target/
         
